/**
 * Task
In this challenge, you are asked to square every digit of a number.

For example, if we run 9119 through the function, 811181 will come out.

Documentation
squareDigits(num)
Parameters:
num: int
The number to process.

Guaranteed Constraints:
It will always be a valid positive integer.
It will never be null or undefined.
Returns: int
The new number generated by squaring each digit of the input number.
 */

fun squareDigits(num: Int): Int {
    val stringNum = num.toString()
    var result = ""
    for(digit in stringNum){
        val temp = digit.toString().toInt()
        result += "${temp*temp}"
    }
    return result.toInt()
}